# Generated by Django 5.2.14 on 2026-06-16 15:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0010_historicallecionamento_dias_semana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistroAula',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('data', models.DateField(db_index=True)),
                ('conteudo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('lancado', 'Lançado'), ('conferido', 'Conferido')], default='rascunho', max_length=20)),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conferido_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.disciplina')),
                ('escola', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.escola')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.professor')),
                ('turma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.turma')),
            ],
            options={
                'verbose_name': 'historical registro de aula',
                'verbose_name_plural': 'historical registros de aula',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegistroAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(db_index=True)),
                ('conteudo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('lancado', 'Lançado'), ('conferido', 'Conferido')], default='rascunho', max_length=20)),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aulas_conferidas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_aula', to='escola.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_aula', to='escola.escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_aula', to='escola.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_aula', to='escola.turma')),
            ],
            options={
                'verbose_name': 'registro de aula',
                'verbose_name_plural': 'registros de aula',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['professor', 'data'], name='aula_idx_prof_data'), models.Index(fields=['escola', 'status'], name='aula_idx_escola_status')],
                'constraints': [models.UniqueConstraint(fields=('escola', 'turma', 'disciplina', 'data'), name='registro_aula_unique_escola_turma_disc_data')],
            },
        ),
    ]
