# Generated by Django 5.2.14 on 2026-06-03 12:46, edited to add a data
# migration that backfills empty emails BEFORE flipping the field to
# blank=False — guarantees the schema constraint never finds a violation
# on existing rows (prod tinha pelo menos um usuário sem email).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_emails_vazios(apps, schema_editor):
    """Preenche email vazio com placeholder `{username}@diariodiniz.local`.

    Idempotente — só toca em rows com email vazio. Não afeta histórico
    (`historicalusuario`) porque a regra de validação só vale pro modelo
    vivo; o histórico mantém o estado original.
    """
    Usuario = apps.get_model("accounts", "Usuario")
    for u in Usuario.objects.filter(email=""):
        u.email = f"{u.username}@diariodiniz.local"
        u.save(update_fields=["email"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalusuario'),
    ]

    operations = [
        migrations.RunPython(preencher_emails_vazios, noop),
        migrations.AlterField(
            model_name='historicalusuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token de redefinição de senha',
                'verbose_name_plural': 'tokens de redefinição de senha',
                'indexes': [models.Index(fields=['usuario', 'usado_em'], name='accounts_pa_usuario_2be9a7_idx')],
            },
        ),
    ]
