# Generated by Django 5.2.14 on 2026-06-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_historicalusuario_email_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Admin'), ('diretor', 'Diretor'), ('professor', 'Professor'), ('secretaria', 'Secretaria'), ('coordenador', 'Coordenador'), ('inspetor', 'Inspetor')], default='professor', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Admin'), ('diretor', 'Diretor'), ('professor', 'Professor'), ('secretaria', 'Secretaria'), ('coordenador', 'Coordenador'), ('inspetor', 'Inspetor')], default='professor', max_length=20),
        ),
    ]
