# Generated by Django 5.2.14 on 2026-05-19 20:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('observacao', models.TextField(blank=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_presenca', to='escola.escola')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_presenca', to='escola.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_presenca', to='escola.turma')),
            ],
            options={
                'verbose_name': 'registro de presença',
                'verbose_name_plural': 'registros de presença',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('R', 'Retardatário')], default='P', max_length=1)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencas', to='escola.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_presenca', to='escola.escola')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='presenca.registropresenca')),
            ],
            options={
                'verbose_name': 'item de presença',
                'verbose_name_plural': 'itens de presença',
                'ordering': ['aluno__nome_completo'],
            },
        ),
        migrations.AddConstraint(
            model_name='registropresenca',
            constraint=models.UniqueConstraint(fields=('escola', 'turma', 'data'), name='registro_presenca_unique_escola_turma_data'),
        ),
        migrations.AddConstraint(
            model_name='itempresenca',
            constraint=models.UniqueConstraint(fields=('registro', 'aluno'), name='item_presenca_unique_registro_aluno'),
        ),
    ]
