# Generated by Django 5.2.14 on 2026-06-12 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0002_historicalitempresenca_historicalregistropresenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistropresenca',
            name='data',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='registropresenca',
            name='data',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
