# Generated by Django 5.2.14 on 2026-06-05 14:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0008_escola_importacao_em_lote_habilitada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriodoAvaliativo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('nome', models.CharField(help_text="Ex.: '1º Bimestre', '2º Trimestre', '1º Semestre'.", max_length=50)),
                ('ordem', models.PositiveSmallIntegerField(help_text='Posição sequencial no ano (1, 2, 3...).')),
                ('ano_letivo', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('escola', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.escola')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical período avaliativo',
                'verbose_name_plural': 'historical períodos avaliativos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PeriodoAvaliativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text="Ex.: '1º Bimestre', '2º Trimestre', '1º Semestre'.", max_length=50)),
                ('ordem', models.PositiveSmallIntegerField(help_text='Posição sequencial no ano (1, 2, 3...).')),
                ('ano_letivo', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_avaliativos', to='escola.escola')),
            ],
            options={
                'verbose_name': 'período avaliativo',
                'verbose_name_plural': 'períodos avaliativos',
                'ordering': ['-ano_letivo', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('escola', 'nome', 'ano_letivo'), name='periodo_unique_escola_nome_ano'), models.UniqueConstraint(fields=('escola', 'ordem', 'ano_letivo'), name='periodo_unique_escola_ordem_ano')],
            },
        ),
    ]
