# Generated by Django 5.2.14 on 2026-06-05 15:48

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('escola', '0008_escola_importacao_em_lote_habilitada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Trabalho'), ('atividade', 'Atividade'), ('participacao', 'Participação')], default='prova', max_length=20)),
                ('data', models.DateField(default=datetime.date.today)),
                ('nota_maxima', models.DecimalField(decimal_places=2, help_text='Valor de referência da avaliação (ex.: 10,00).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Peso pra média ponderada — usado pela escola fora do sistema.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ativo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='escola.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='escola.escola')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='avaliacao.periodoavaliativo')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='escola.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='escola.turma')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAvaliacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Trabalho'), ('atividade', 'Atividade'), ('participacao', 'Participação')], default='prova', max_length=20)),
                ('data', models.DateField(default=datetime.date.today)),
                ('nota_maxima', models.DecimalField(decimal_places=2, help_text='Valor de referência da avaliação (ex.: 10,00).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Peso pra média ponderada — usado pela escola fora do sistema.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('disciplina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.disciplina')),
                ('escola', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.escola')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='avaliacao.periodoavaliativo')),
                ('professor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.professor')),
                ('turma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.turma')),
            ],
            options={
                'verbose_name': 'historical avaliação',
                'verbose_name_plural': 'historical avaliações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNotaAvaliacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacao', models.CharField(blank=True, help_text='Nota interna do professor — não aparece no boletim do responsável.', max_length=300)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aluno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.aluno')),
                ('avaliacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='avaliacao.avaliacao')),
                ('escola', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.escola')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nota de avaliação',
                'verbose_name_plural': 'historical notas de avaliação',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NotaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacao', models.CharField(blank=True, help_text='Nota interna do professor — não aparece no boletim do responsável.', max_length=300)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_avaliacao', to='escola.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='avaliacao.avaliacao')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_avaliacao', to='escola.escola')),
            ],
            options={
                'verbose_name': 'nota de avaliação',
                'verbose_name_plural': 'notas de avaliação',
                'ordering': ['aluno__nome_completo'],
                'constraints': [models.UniqueConstraint(fields=('avaliacao', 'aluno'), name='nota_avaliacao_unique_avaliacao_aluno')],
            },
        ),
    ]
