# Generated by Django 5.2.14 on 2026-06-05 18:25

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_migrar_tarefas'),
        ('escola', '0008_escola_importacao_em_lote_habilitada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNotaPeriodo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Média final do período — digitada pelo professor.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacao', models.CharField(blank=True, help_text='Nota interna do professor — não aparece no boletim do responsável.', max_length=300)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aluno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.aluno')),
                ('disciplina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.disciplina')),
                ('escola', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.escola')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='avaliacao.periodoavaliativo')),
            ],
            options={
                'verbose_name': 'historical nota de período',
                'verbose_name_plural': 'historical notas de período',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NotaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Média final do período — digitada pelo professor.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacao', models.CharField(blank=True, help_text='Nota interna do professor — não aparece no boletim do responsável.', max_length=300)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_periodo', to='escola.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_periodo', to='escola.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_periodo', to='escola.escola')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_periodo', to='avaliacao.periodoavaliativo')),
            ],
            options={
                'verbose_name': 'nota de período',
                'verbose_name_plural': 'notas de período',
                'ordering': ['-periodo__ano_letivo', 'periodo__ordem', 'aluno__nome_completo'],
                'constraints': [models.UniqueConstraint(fields=('escola', 'aluno', 'disciplina', 'periodo'), name='nota_periodo_unique_aluno_disc_periodo')],
            },
        ),
    ]
