# Generated by Django 5.2.14 on 2026-06-12 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_historicalnotaperiodo_notaperiodo'),
        ('escola', '0009_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historicalavaliacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='historicalavaliacao',
            name='data',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AddIndex(
            model_name='notaperiodo',
            index=models.Index(fields=['disciplina', 'periodo', 'aluno'], name='nota_periodo_idx_disc_per_alu'),
        ),
    ]
