# Generated by Django 5.2.14 on 2026-05-25 14:17

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_lancamento', models.DateField(default=datetime.date.today)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('vale_nota', models.BooleanField(default=False)),
                ('nota_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='escola.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='escola.escola')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='escola.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='escola.turma')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['-data_lancamento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EntregaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('entregue', models.BooleanField(default=False)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_tarefas', to='escola.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_tarefas', to='escola.escola')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'entrega de tarefa',
                'verbose_name_plural': 'entregas de tarefa',
                'ordering': ['aluno__nome_completo'],
                'constraints': [models.UniqueConstraint(fields=('tarefa', 'aluno'), name='entrega_unique_tarefa_aluno')],
            },
        ),
    ]
