# Generated by Django 5.2.17 on 2026-10-06 11:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escola", "0010_historicallecionamento_dias_semana_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalResponsavel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("email", models.EmailField(max_length=254)),
                ("nome", models.CharField(max_length=200)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="escola.escola",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical responsável",
                "verbose_name_plural": "historical responsáveis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("nome", models.CharField(max_length=200)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsaveis",
                        to="escola.escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "responsável",
                "verbose_name_plural": "responsáveis",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalResponsavelAluno",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="escola.aluno",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.responsavel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo responsável/aluno",
                "verbose_name_plural": "historical vínculos responsável/aluno",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ResponsavelAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_responsavel",
                        to="escola.aluno",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos",
                        to="portal.responsavel",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo responsável/aluno",
                "verbose_name_plural": "vínculos responsável/aluno",
                "ordering": ["aluno__nome_completo"],
            },
        ),
        migrations.AddField(
            model_name="responsavel",
            name="alunos",
            field=models.ManyToManyField(
                related_name="responsaveis",
                through="portal.ResponsavelAluno",
                to="escola.aluno",
            ),
        ),
        migrations.AddIndex(
            model_name="responsavelaluno",
            index=models.Index(
                fields=["responsavel"], name="respaluno_idx_responsavel"
            ),
        ),
        migrations.AddConstraint(
            model_name="responsavelaluno",
            constraint=models.UniqueConstraint(
                fields=("responsavel", "aluno"),
                name="responsavelaluno_unique_responsavel_aluno",
            ),
        ),
        migrations.AddConstraint(
            model_name="responsavel",
            constraint=models.UniqueConstraint(
                fields=("escola", "email"), name="responsavel_unique_escola_email"
            ),
        ),
    ]
