# Generated by Django 5.2.14 on 2026-10-06 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalidade', models.CharField(choices=[('convite', 'Convite'), ('redefinicao', 'Redefinição de senha')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_responsavel', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites', to='portal.responsavel')),
            ],
            options={
                'verbose_name': 'convite de responsável',
                'verbose_name_plural': 'convites de responsável',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['responsavel', 'usado_em'], name='portal_conv_respons_90cb1f_idx')],
            },
        ),
    ]
