# Generated by Django 5.2.17 on 2026-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_responsavel_senha_vazia"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresponsavel",
            name="recebe_notificacao",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="responsavel",
            name="recebe_notificacao",
            field=models.BooleanField(default=True),
        ),
    ]
