# Generated by Django 5.2.17 on 2026-10-06 09:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escola", "0010_historicallecionamento_dias_semana_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunicado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "destino",
                    models.CharField(
                        choices=[
                            ("escola", "Toda a escola"),
                            ("turmas", "Turmas selecionadas"),
                        ],
                        default="escola",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviando", "Enviando"),
                            ("enviado", "Enviado"),
                            ("falhou", "Falhou"),
                        ],
                        db_index=True,
                        default="rascunho",
                        max_length=10,
                    ),
                ),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("total_destinatarios", models.PositiveIntegerField(default=0)),
                ("total_enviados", models.PositiveIntegerField(default=0)),
                ("total_falhas", models.PositiveIntegerField(default=0)),
                ("total_sem_email", models.PositiveIntegerField(default=0)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicados_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicados_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comunicados",
                        to="escola.escola",
                    ),
                ),
                (
                    "turmas",
                    models.ManyToManyField(
                        blank=True, related_name="comunicados", to="escola.turma"
                    ),
                ),
            ],
            options={
                "verbose_name": "comunicado",
                "verbose_name_plural": "comunicados",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ComunicadoDestinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("nome_responsavel", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviado", "Enviado"),
                            ("falhou", "Falhou"),
                            ("sem_email", "Sem email cadastrado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("erro", models.TextField(blank=True)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comunicados_recebidos",
                        to="escola.aluno",
                    ),
                ),
                (
                    "comunicado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinatarios",
                        to="comunicados.comunicado",
                    ),
                ),
            ],
            options={
                "verbose_name": "destinatário de comunicado",
                "verbose_name_plural": "destinatários de comunicado",
                "ordering": ["aluno__nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalComunicado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "destino",
                    models.CharField(
                        choices=[
                            ("escola", "Toda a escola"),
                            ("turmas", "Turmas selecionadas"),
                        ],
                        default="escola",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviando", "Enviando"),
                            ("enviado", "Enviado"),
                            ("falhou", "Falhou"),
                        ],
                        db_index=True,
                        default="rascunho",
                        max_length=10,
                    ),
                ),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("total_destinatarios", models.PositiveIntegerField(default=0)),
                ("total_enviados", models.PositiveIntegerField(default=0)),
                ("total_falhas", models.PositiveIntegerField(default=0)),
                ("total_sem_email", models.PositiveIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="escola.escola",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical comunicado",
                "verbose_name_plural": "historical comunicados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalComunicado_turmas",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "comunicado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="comunicados.comunicado",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="comunicados.historicalcomunicado",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="escola.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalComunicado_turmas",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="comunicado",
            index=models.Index(
                fields=["escola", "-criado_em"], name="comunicado_idx_escola_criado"
            ),
        ),
        migrations.AddIndex(
            model_name="comunicadodestinatario",
            index=models.Index(
                fields=["comunicado", "status"], name="comunicado_dest_idx_com_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="comunicadodestinatario",
            constraint=models.UniqueConstraint(
                fields=("comunicado", "aluno"),
                name="comunicado_dest_unique_comunicado_aluno",
            ),
        ),
    ]
