# Generated by Django 5.2.17 on 2026-10-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicados", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicadodestinatario",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("enviando", "Envio não confirmado"),
                    ("enviado", "Enviado"),
                    ("falhou", "Falhou"),
                    ("sem_email", "Sem email cadastrado"),
                ],
                default="pendente",
                max_length=10,
            ),
        ),
    ]
