# Generated by Django 5.2.17 on 2026-10-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicados", "0002_alter_comunicadodestinatario_status"),
        ("escola", "0010_historicallecionamento_dias_semana_and_more"),
        ("portal", "0004_responsavel_recebe_notificacao"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comunicadodestinatario",
            name="comunicado_dest_unique_comunicado_aluno",
        ),
        migrations.AddField(
            model_name="comunicadodestinatario",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comunicados_recebidos",
                to="portal.responsavel",
            ),
        ),
        migrations.AddConstraint(
            model_name="comunicadodestinatario",
            constraint=models.UniqueConstraint(
                fields=("comunicado", "aluno", "responsavel"),
                name="comunicado_dest_unique_com_aluno_resp",
                nulls_distinct=False,
            ),
        ),
    ]
