# Generated by Django 5.2.14 on 2026-05-08 01:13

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[apps.common.validators.validar_cnpj]),
        ),
    ]
