# Generated by Django 5.2.14 on 2026-05-08 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_escola_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='professores', to='escola.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professores', to='escola.escola')),
                ('usuario', models.OneToOneField(limit_choices_to={'perfil': 'professor'}, on_delete=django.db.models.deletion.PROTECT, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
    ]
