# Generated by Django 5.2.14 on 2026-05-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_seed_disciplinas_comuns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplinas',
        ),
        migrations.CreateModel(
            name='Lecionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecionamentos', to='escola.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecionamentos', to='escola.escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecionamentos', to='escola.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecionamentos', to='escola.turma')),
            ],
            options={
                'verbose_name': 'lecionamento',
                'verbose_name_plural': 'lecionamentos',
                'ordering': ['turma__ano_letivo', 'turma__nome', 'disciplina__nome'],
                'constraints': [models.UniqueConstraint(fields=('professor', 'turma', 'disciplina'), name='lecionamento_unique_prof_turma_disc')],
            },
        ),
    ]
