# Generated by Django 5.2.14 on 2026-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_remove_professor_disciplinas_lecionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
