# Generated by Django 5.2.14 on 2026-06-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_escola_importacao_em_lote_habilitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['turma', 'ativo'], name='aluno_idx_turma_ativo'),
        ),
        migrations.AddIndex(
            model_name='lecionamento',
            index=models.Index(fields=['professor', 'ativo'], name='lecionamento_idx_prof_ativo'),
        ),
    ]
