# Generated by Django 5.2.14 on 2026-06-16 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallecionamento',
            name='dias_semana',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='lecionamento',
            name='dias_semana',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')]), blank=True, default=list, size=None),
        ),
    ]
