# Generated by Django 5.2.14 on 2026-05-25 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano_letivo', models.PositiveIntegerField()),
                ('ementa', models.TextField(blank=True)),
                ('conteudo_programatico', models.TextField(blank=True)),
                ('objetivos_gerais', models.TextField(blank=True)),
                ('objetivos_especificos', models.TextField(blank=True)),
                ('habilidades_bncc', models.TextField(blank=True, help_text='Códigos da BNCC, um por linha (ex.: EF06MA01).')),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('avaliacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_ensino', to='escola.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_ensino', to='escola.escola')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos_ensino', to='escola.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_ensino', to='escola.turma')),
            ],
            options={
                'verbose_name': 'plano de ensino',
                'verbose_name_plural': 'planos de ensino',
                'ordering': ['-ano_letivo', 'turma__nome', 'disciplina__nome'],
                'constraints': [models.UniqueConstraint(fields=('escola', 'turma', 'disciplina', 'ano_letivo'), name='plano_ensino_unique_escola_turma_disciplina_ano')],
            },
        ),
    ]
