# Generated by Django 5.2.14 on 2026-05-28 18:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_historicalaluno_historicallecionamento_and_more'),
        ('planos_ensino', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlanoEnsino',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ano_letivo', models.PositiveIntegerField()),
                ('ementa', models.TextField(blank=True)),
                ('conteudo_programatico', models.TextField(blank=True)),
                ('objetivos_gerais', models.TextField(blank=True)),
                ('objetivos_especificos', models.TextField(blank=True)),
                ('habilidades_bncc', models.TextField(blank=True, help_text='Códigos da BNCC, um por linha (ex.: EF06MA01).')),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('avaliacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('disciplina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.disciplina')),
                ('escola', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.escola')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.professor')),
                ('turma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.turma')),
            ],
            options={
                'verbose_name': 'historical plano de ensino',
                'verbose_name_plural': 'historical planos de ensino',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
