# Generated by Django 5.2.14 on 2026-05-19 19:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField()),
                ('data_ocorrencia', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('resolvida', 'Resolvida'), ('arquivada', 'Arquivada')], default='aberta', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='escola.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='escola.escola')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='escola.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='escola.turma')),
            ],
            options={
                'verbose_name': 'ocorrência',
                'verbose_name_plural': 'ocorrências',
                'ordering': ['-data_ocorrencia', '-criado_em'],
            },
        ),
    ]
