# Generated by Django 5.2.14 on 2026-06-12 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_historicalocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalocorrencia',
            name='data_ocorrencia',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historicalocorrencia',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('resolvida', 'Resolvida'), ('arquivada', 'Arquivada')], db_index=True, default='aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_ocorrencia',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('resolvida', 'Resolvida'), ('arquivada', 'Arquivada')], db_index=True, default='aberta', max_length=20),
        ),
    ]
